### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by wolfsberger** [MemOrg/RESTSamples#1]

**Comment by mempfennig** [comment]
123

**Comment by mempfennig** [comment]
Ok!

Mit freundlichen Grüßen | Kind regards

i.A. Stefan Pfennig (Mr)
Entwicklung

Von: wolfsberger [mailto:notifications@github.com]
Gesendet: Freitag, 16. Oktober 2015 12:15
An: MemOrg/RESTSamples
Cc: Stefan Pfennig
Betreff: Re: [RESTSamples] No content (#1)


Assigned #1<https://github.com/MemOrg/RESTSamples/issues/1> to @mempfennig<https://github.com/mempfennig>.

**Comment by mempfennig** [comment]
jojojo

Mit freundlichen Grüßen | Kind regards

i.A. Stefan Pfennig (Mr)
Entwicklung

Von: wolfsberger [mailto:notifications@github.com]
Gesendet: Freitag, 16. Oktober 2015 12:15
An: MemOrg/RESTSamples
Betreff: [RESTSamples] No content (#1)

**Comment by wolfsberger** [comment]
Blub
